//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionEmploi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class emploie
    {
        public int idEmploie { get; set; }
        public System.DateTime Jours { get; set; }
        public System.TimeSpan heure_debut { get; set; }
        public System.TimeSpan heure_fin { get; set; }
        public int FormateurIdFormateur { get; set; }
        public int Groupe_idGroupe { get; set; }
        public int Module_idModule { get; set; }
    
        public virtual Formateur Formateur { get; set; }
        public virtual Groupe Groupe { get; set; }
        public virtual Module Module { get; set; }
    }
}
